#!/bin/bash

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

cp nginx-instaban /usr/bin/nginx-instaban

cp initscript.sh /etc/init.d/nginx-instaban
/bin/chmod +x  /etc/init.d/nginx-instaban

cp nginx-instaban.service /lib/systemd/system/nginx-instaban.service
/bin/chmod +x  /lib/systemd/system/nginx-instaban.service

cp example.nginx-instaban.conf /etc/nginx-instaban.conf

touch /var/log/nginx-instaban.log
