#!/bin/bash

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

rm /usr/bin/nginx-instaban
rm /etc/init.d/nginx-instaban
rm /lib/systemd/system/nginx-instaban.service
rm etc/nginx-instaban.conf
rm /var/log/nginx-instaban.log
